name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload to Server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp://your-bigrock-ftp-server
          username: ${{ secrets.BIGROCK_FTP_USER }}
          password: ${{ secrets.BIGROCK_FTP_PASSWORD }}
          local-dir: ./frontend/.next
          server-dir: /public_html/frontend